import type { Metadata } from "next";
import "./globals.css";

import { Toaster } from "react-hot-toast";

import { Plus_Jakarta_Sans } from "@next/font/google";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import { AppProvider } from "../contexts/AppContext";
import { AuthProvider } from "../contexts/AuthContext";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "500", "700"], // Specify weights as needed
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.className} antialiased overflow-x-hidden`}
      >
        <AuthProvider>
          <AppProvider>
            <div
            // style={
            //   isDashboardPage
            //     ? { display: "grid", gridTemplateRows: "auto 1fr" }
            //     : {}
            // }
            // className={`${isDashboardPage ? "min-h-screen" : ""}`}
            >
              <Navbar />
              <div className="mt-16">{children}</div>
            </div>
            <Footer />
          </AppProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
