import type { Metadata } from "next";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";

<<<<<<< HEAD
import { Toaster } from "react-hot-toast";
import { UserAuthProvider } from "./_contexts/UserAuthContext";
=======
import { Plus_Jakarta_Sans } from "next/font/google";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import { usePathname } from "next/navigation";
import { AppProvider } from "../contexts/AppContext";
import { AuthProvider } from "../contexts/AuthContext";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "500", "700"], // Specify weights as needed
});
>>>>>>> 983440d994ae631074b4b7ca8ab9d2e0e90831bf

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-[85%] md:text[90%] lg:text-[95%]">
      <body className={`antialiased overflow-x-hidden no-scrollbar`}>
        <GoogleOAuthProvider clientId="353332526572-1f03a2r0gstceibcvhtlnfg9eo3gsq8r.apps.googleusercontent.com">
          <UserAuthProvider>{children}</UserAuthProvider>
        </GoogleOAuthProvider>
        <Toaster
          toastOptions={{
            success: {
              duration: 3000,
              style: { background: "#4CAF50", color: "#fff" },
            },
            error: {
              duration: 5000,
              style: { background: "#F44336", color: "#fff" },
            },
            loading: {
              duration: 3000,
              style: { background: "#FF9800", color: "#fff" },
            },
          }}
        />
      </body>
    </html>
  );
}
